name: Continuos Integration

on: push

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar respositório
        uses: actions/checkout@v3
        
      - name: Mostrar informações do github
        run: echo "$GITHUB_CONTEXT"

      - name: Configurar ambiente para testes
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install pytest
          pip3 install pytest-cov

      - name: Instalar compilador c
        uses: aminya/setup-cpp@v1

      - name: Compilar o arquivo
        run: gcc main.c -o main
        
      - name: Rodar testes com pytest
        continue-on-error: true
        run: pytest --junitxml=results.xml . 
    
      - uses: actions/upload-artifact@v3
        with:
          name: code-covarage-report
          path: results.xml

      - name: Enviar resultados para o repositório
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add results.xml
          git commit -m "Adicionando/atualizando resultados"
          git push
